matrix:
  include:
    - language: node_js
      node_js:
        - stable
      before_script:
        - cd api
        - npm install
      cache:
        directories:
          - api/node_modules
      script:
        - npm test
      before_deploy:
        - npm run clean-modules
      deploy:
        provider: lambda
        function_name: SWoT
        region: us-east-1
        role: arn:aws:iam::578324725290:role/service-role/lambdarole
        runtime: nodejs6.10
        module_name: src/index
        handler_name: handler
        access_key_id: AKIAILRZNTSHNQYX2NYQ
        secret_access_key:
          secure: LkJWoZOmqB1h/ZFCbf+qK4rpKFS2zJdgR/gK5Drfkqz7KjUsgUCSqGRlMOc3fFiMNUOivIq/mEORuM/6i31quMlJNLpFZcFG4KbXikeFGroQchC+swuMLZEmh03PKlKVcB2I91g66lcsBD9p0Iv+pVTiBcs0d3H+TS20oVHFjmlHJPM/oaRN2IGsU4jvCN4bPZFJekHkY2QRvI7jTZYIIideyWTev2xoPSiUy4NvW4ZNjC0wgt8WQ/8sKLWKvtcVpdPWwIJmN300tP2lq6oBUWmST2q5cm0QlHpiBOys8aG2SMMiePQFxBFwlNwTqm/qvBUTgLbF9xiZD0tC0FrrRfpoqOQNg3C+kiJIisDGl/fdNXWSS2XySAiSG2yYEdnOmhBc5KxwqgBGLVb4Fm0WX0BOqIZeFbCftslTJepJAicoB6Vh5PllUp50WspWsBdkCKo84x8kAoLaVQkvL3QKGw7tR7KZGS68SE3ABPGkrr0+fVak97a/oaS9fY0XNs2PZggVgn9emlhgASfc+acRxPJ6VSmyGB+ICeITaNLWtXVjbTLQPU2QEDWx6szolMivCghvzIl8b/qh7MdJ+fBJJfYhsAQXlW9k98wRum9KyT27HXLDSC1Y85Nl1TFuba9I1D8dtHhZL1AjRrbYCgeXlNHvq7Q+A9YM6BC6iR9qKK4=
        on:
          repo: jpdillingham/SWoT
          branch: master
    - language: node_js
      node_js:
        - "stable"
      before_script:
        - cd web
        - npm install
      cache:
        directories:
        - web/node_modules
      script:
        - npm test
        - npm run build
      deploy:
        provider: s3
        access_key_id: AKIAIAMHE73TSFTKF4SQ
        secret_access_key:
          secure: JuDtxp4QZnXMda0uaRhZMJsVGMFyzjmnraNJGkFR+uqO9EsJxmxAnc1KEu71AwUgnjbsnBmreq9VGJ4JZc0B89QMgSbdJDrWTd1YE79mc+01dUHcBsVtJ5dIB+00nnq9PvNe0CGDqd73tVBpyrJzY1ArWxqHP3SSysX9xOVQm3gTGhQQyc1AKS8KP2MkPyLI9BhgbGw4A3e0TYc7ZuZJkzjKIuj4Aay3xQ5XNB6MM/U7iS3Hi3t++88CtEgWkbLexcIHJ9h+ckoP2WtMdaonFLZyUdAE12+CMeQQm/3fPDCrbfRlhme9L3ZipXyHi/smQM1Fun9yBCsXXT4h3AfQSuYb1+PhL55vdAcseP21yZkxnTL27RQONy4YHyc7YTXJliJ2MdjrKXkJvH12x/+Y+KSeet+SPGM3m5T0u3bhAYNqUk9V65g6KrCmPEfDOlN8ej+kdYF1emspoBlNTHRlVNYGfvG99dRAwYotEM57MFYHSbjhE2fWf8j0mtSNtNnOzsUR005IGruFCXGqZsN88Yp4jhBwJ0afi1AAaEaGBiFF9XxgBKreCBE53mql0dxuG5Ukeysv5DjxyByo4r5v4dNlT16mk9jLxln+Ze4lPFSn9se8uAmRYp07HbRzr0W6tuEbL2W3cuXrNIXBhepQVpHjeBuQ0iFNi4UQroXsACQ=
        bucket: swot-content
        skip_cleanup: true
        local_dir: build
        region: us-east-1
        acl: public_read
        on:
          repo: jpdillingham/SWoT
          branch: master

