info:
  title: SWoT
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'

paths:
  /exercises/:
    get:
      operationId: get-exercises
      summary: Gets a list of configured Exercises
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/exercise'
    post:
      operationId: CreateCluster
      summary: Create a cluster
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/exercise'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/exercise'

definitions:
  exercise:
    type: object
    properties:
      id:
        description: Unique identifier for the Exercise
        type: string
      name:
        description: The display name of the Exercise
        type: string
      type:
        description: The Exercise type (weightlifting, cardio, stretching, balance)
        type: string
      url:
        description: A url to a description of the Exercise
        type: string
      metrics:
        $ref: '#/definitions/metric'
  metric:
    type: object
    required: [ name ]
    properties:
      name:
        description: The name of the Metric
        type: string
      uom:
        description: The unit of measure
        type: string
      value:
        description: The result value
        type: string