info:
  title: SWoT
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'

paths:
  /exercises/:
    get:
      summary: Gets a list of configured Exercises
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/exercise'
        500:
          description: Error
    post:
      summary: Adds an Exercise
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/exercise'
      parameters:
        - name: Exercise
          in: body
          required: true
          schema:
            $ref: '#/definitions/exercise'
    put:
      summary: Updates an Exercise
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/exercise'
        500:
          description: Error
      parameters:
        - name: exerciseId
          in: path
          required: true
          type: string
        - name: exercise
          in: body
          required: true
          schema:
            $ref: '#/definitions/exercise'

definitions:
  exercise:
    type: object
    properties:
      id:
        description: Unique identifier for the Exercise
        type: string
      name:
        description: The display name of the Exercise
        type: string
      type:
        description: The Exercise type (weightlifting, cardio, stretching, balance)
        type: string
      url:
        description: A url to a description of the Exercise
        type: string
      metrics:
        type: array
        items:
          $ref: '#/definitions/metric'
  metric:
    type: object
    required: [ name ]
    properties:
      name:
        description: The name of the Metric
        type: string
      uom:
        description: The unit of measure
        type: string
      value:
        description: The result value
        type: string
  routine:
    type: object
    properties:
      id:
        description: Unique identifier for the Routine
        type: string
      name:
        description: The display name of the Routine
        type: string
      color:
        description: The hexadecimal color code for the Routine
        type: string
      exercises:
        type: array
        items:
          $ref: '#/definitions/exercise'
  workout:
    type: object
    properties:
      id: 
        description: Unique identifier for the Workout
        type: string
      scheduledTime:
        description: The unix timestamp of the time for which the Workout was scheduled
        type: integer
      startTime:
        description: The unix timestamp of the time at which the Workout was started
        type: integer
      endTime:
        description: The unix timestamp of the time at which the Workout ended
        type: integer
      routine:
        $ref: '#/definitions/routine'
      notes:
        description: Notes entered during the Workout
        type: string