info:
  title: SWoT
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
swagger: '2.0'

security: []

paths:
  /exercises/:
    get:
      operationId: GetExercises
      summary: Get list of configured Exercises
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Cluster'
      security:
        - keystone: []
    post:
      operationId: CreateCluster
      summary: Create a cluster
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Cluster'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Cluster'
      security:
        - keystone: []

definitions:
  Cluster:
    type: object
    properties:
      name:
        description: name of the cluster
        type: string